### ISSUE TITLE
[REVIEW] of lesson: Unicode

### ISSUE THREAD

**Issue by Habenzy** [BurlingtonCodeAcademy/codelikethis#225]
**Should we keep this lesson?**
- [ ] YES
- [x] NO

**Lesson Quality**
- [x] LOW
- [ ] MED
- [ ] HIGH

**LAB(s) included in the lesson?**
- [ ] YES
- [x] NO
- [ ] NOT SUFFICIENT

**Lesson taught in full-time course week**
- [x] Week-1
- [ ] Week-2
- [ ] Week-3
- [ ] Week-4
- [ ] Week-5
- [ ] Week-6
- [ ] Week-7
- [ ] Week-8

**Additional Information**
Unfinished. All the info that's there is already covered in the 'Strings' lesson.

[Unicode Lesson Link](https://github.com/BurlingtonCodeAcademy/codelikethis/blob/master/public/lessons/javascript/unicode.md)

**Comment by Dangeranger** [comment]
Duplicate issue.
