### ISSUE TITLE
[REVIEW] of General Course, Fall-2020

### ISSUE THREAD

**Issue by Dangeranger** [BurlingtonCodeAcademy/codelikethis#235]
Please leave your general comments about the course, and any specific changes to lessons that you feel are necessary for future cohorts.

Add your thoughts as comments below attached to this issue.

**Comment by Habenzy** [comment]
The [Input and Output](https://github.com/BurlingtonCodeAcademy/codelikethis/blob/master/public/lessons/javascript/input_and_output.md), and [Evented I/O](https://github.com/BurlingtonCodeAcademy/codelikethis/blob/master/public/lessons/javascript/evented_io.md) lessons could be combined, and consolidated.
