### ISSUE TITLE
[REVIEW] of lesson: Error Boundaries

### ISSUE THREAD

**Issue by DevonSmith91** [BurlingtonCodeAcademy/codelikethis#260]
**Should we keep this lesson?**
- [x] YES
- [ ] NO

**Lesson Quality**
- [ ] LOW
- [ ] MED
- [ ] HIGH

**LAB(s) included in the lesson?**
- [ ] YES
- [ ] NO
- [x] NOT SUFFICIENT

**Lesson taught in full-time course week**
- [ ] Week-1
- [ ] Week-2
- [ ] Week-3
- [ ] Week-4
- [x] Week-5
- [ ] Week-6
- [ ] Week-7
- [ ] Week-8

**Additional Information**
This lesson generally gets taught as a bonus lesson during capstone weeks. Would it be practical to move the location of this to something more of a "Bonus Topic" type folder to keep the curriculum folders more organize? 

This is also written entirely as class based components

[Lesson Link](https://bootcamp.burlingtoncodeacademy.com/lessons/react/error-boundaries)

**Comment by Habenzy** [comment]
Currently React doesn't have a hook for `componentDidCatch` so error boundaries can only be set in a class based component. They do plan to add a hook for it eventually though.
