### ISSUE TITLE
State Machines lesson link is broken.

### ISSUE THREAD

**Issue by Dangeranger** [BurlingtonCodeAcademy/codelikethis#86]
There was a lesson on the conceptual model of state machine in computer science, with some good explanations about how they work and how to build them.

We need that lesson so that people have some hints about how to approach the Zorkington lab.

Here is the line in question:
https://github.com/BurlingtonCodeAcademy/codelikethis/blame/master/public/projects/zorkington.md#L58

**Comment by Habenzy** [comment]
I'll go ahead and fix that link.  I'm pretty sure I didn't delete that lesson, but if I did I've got a backup I can pull it from, and add it back in easily enough.
